# Generated by Django 3.1.2 on 2020-10-16 00:57

from django.db import migrations, models
import django.db.models.deletion
import shortuuidfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0019_auto_20201016_0554'),
    ]

    operations = [
        migrations.CreateModel(
            name='PunchRecord',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('creator_id', models.CharField(max_length=100, verbose_name='创建人')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('modifier_id', models.CharField(max_length=100, verbose_name='修改人')),
                ('is_del', models.BooleanField(default=False, verbose_name='是否删除')),
                ('delete_time', models.DateTimeField(null=True, verbose_name='删除时间')),
                ('deleter_id', models.CharField(max_length=100, verbose_name='删除人')),
                ('id', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, primary_key=True, serialize=False)),
                ('punch_time', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('punch_point', models.CharField(max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.orgdepartment')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
            options={
                'db_table': 'punch_record',
            },
        ),
        migrations.AddIndex(
            model_name='punchrecord',
            index=models.Index(fields=['employee', 'punch_time'], name='punch_recor_employe_758810_idx'),
        ),
        migrations.AddIndex(
            model_name='punchrecord',
            index=models.Index(fields=['department', 'punch_time'], name='punch_recor_departm_3d4f84_idx'),
        ),
    ]
