# Generated by Django 3.1.3 on 2020-11-11 15:32

import apps.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orgs', '0001_initial'),
        ('emp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobInformation',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('creator_id', models.CharField(max_length=100, verbose_name='创建人')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('modifier_id', models.CharField(max_length=100, verbose_name='修改人')),
                ('is_del', models.BooleanField(default=False, verbose_name='是否删除')),
                ('delete_time', models.DateTimeField(null=True, verbose_name='删除时间')),
                ('deleter_id', models.CharField(max_length=100, verbose_name='删除人')),
                ('id', apps.fields.LowerCaseShortUUIDField(blank=True, editable=False, max_length=22, primary_key=True, serialize=False)),
                ('begin_date', models.DateField()),
                ('end_date', models.DateField()),
                ('position_type', models.IntegerField(choices=[(0, '主任职'), (1, '兼职'), (2, '借调'), (3, '委派'), (4, '助勤'), (5, '挂职')])),
                ('position_status', models.IntegerField(choices=[(0, '在职'), (1, '试用'), (2, '离职')])),
                ('department', apps.fields.ForeignKeyWithOutDBConstraint(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='orgs.orgdepartment')),
                ('employee', apps.fields.ForeignKeyWithOutDBConstraint(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='emp.employee')),
                ('position', apps.fields.ForeignKeyWithOutDBConstraint(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='orgs.position')),
                ('unit', apps.fields.ForeignKeyWithOutDBConstraint(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='orgs.orgunit')),
            ],
            options={
                'db_table': 'jobinformation',
            },
        ),
    ]
