# Generated by Django 3.1.2 on 2020-10-12 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_auto_20201012_2240'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserToEmployee',
        ),
    ]
