# Generated by Django 3.1.2 on 2020-10-12 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_auto_20201012_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.IntegerField(choices=[(0, '女'), (1, '男'), (2, '其他')], null=True),
        ),
    ]
