# Generated by Django 3.1.2 on 2020-10-13 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_auto_20201013_0812'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='uid',
            new_name='user',
        ),
    ]
