# Generated by Django 3.1.2 on 2020-10-13 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_auto_20201013_0833'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='telephone',
            new_name='mobile',
        ),
        migrations.AddField(
            model_name='employee',
            name='id_type',
            field=models.IntegerField(choices=[(0, '身份证'), (1, '港澳台身份证'), (2, '外国护照')], default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='photo',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
