# Generated by Django 3.1.2 on 2020-10-13 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0011_auto_20201013_1512'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='jobinformation',
            table='jobinformation',
        ),
        migrations.AlterModelTable(
            name='orgdepartment',
            table='org_department',
        ),
        migrations.AlterModelTable(
            name='orgunit',
            table='org_unit',
        ),
        migrations.AlterModelTable(
            name='position',
            table='position',
        ),
    ]
