# Generated by Django 3.1.2 on 2020-10-13 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0012_auto_20201013_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orgdepartment',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orgdepartment',
            name='number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orgunit',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orgunit',
            name='number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
