# Generated by Django 3.1.2 on 2020-10-13 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0015_auto_20201013_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgdepartment',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.orgdepartment'),
        ),
        migrations.AlterField(
            model_name='orgunit',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.orgunit'),
        ),
    ]
