# Generated by Django 3.1.2 on 2020-10-14 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0017_auto_20201013_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
