# Generated by Django 3.1.2 on 2020-10-12 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='delete_time',
            field=models.DateTimeField(null=True, verbose_name='删除时间'),
        ),
    ]
