# Generated by Django 3.1.3 on 2020-11-11 15:31

import apps.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('creator_id', models.CharField(max_length=100, verbose_name='创建人')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('modifier_id', models.CharField(max_length=100, verbose_name='修改人')),
                ('is_del', models.BooleanField(default=False, verbose_name='是否删除')),
                ('delete_time', models.DateTimeField(null=True, verbose_name='删除时间')),
                ('deleter_id', models.CharField(max_length=100, verbose_name='删除人')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('id', apps.fields.LowerCaseShortUUIDField(blank=True, editable=False, max_length=22, primary_key=True, serialize=False)),
                ('age', models.IntegerField(null=True)),
                ('gender', models.IntegerField(choices=[(0, '女'), (1, '男'), (2, '其他')], null=True)),
                ('id_type', models.IntegerField(choices=[(0, '身份证'), (1, '港澳台身份证'), (2, '外国护照')], default=0)),
                ('identity_card', models.CharField(max_length=18)),
                ('mobile', models.CharField(max_length=11)),
                ('photo', models.CharField(max_length=100, null=True)),
                ('entry_status', models.PositiveIntegerField(choices=[(0, '未入职'), (1, '已入职')], default=0)),
                ('user', models.OneToOneField(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'employee',
            },
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['user'], name='employee_user_id_7ab7e5_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['mobile'], name='employee_mobile_1d49db_idx'),
        ),
    ]
