# Generated by Django 3.1.3 on 2020-11-11 15:31

import apps.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrgDepartment',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('creator_id', models.CharField(max_length=100, verbose_name='创建人')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('modifier_id', models.CharField(max_length=100, verbose_name='修改人')),
                ('is_del', models.BooleanField(default=False, verbose_name='是否删除')),
                ('delete_time', models.DateTimeField(null=True, verbose_name='删除时间')),
                ('deleter_id', models.CharField(max_length=100, verbose_name='删除人')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('id', apps.fields.LowerCaseShortUUIDField(blank=True, editable=False, max_length=22, primary_key=True, serialize=False)),
                ('begin_date', models.DateField()),
                ('end_date', models.DateField()),
                ('parent', apps.fields.ForeignKeyWithOutDBConstraint(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='orgs.orgdepartment')),
            ],
            options={
                'db_table': 'org_department',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('creator_id', models.CharField(max_length=100, verbose_name='创建人')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('modifier_id', models.CharField(max_length=100, verbose_name='修改人')),
                ('is_del', models.BooleanField(default=False, verbose_name='是否删除')),
                ('delete_time', models.DateTimeField(null=True, verbose_name='删除时间')),
                ('deleter_id', models.CharField(max_length=100, verbose_name='删除人')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('id', apps.fields.LowerCaseShortUUIDField(blank=True, editable=False, max_length=22, primary_key=True, serialize=False)),
                ('begin_date', models.DateField()),
                ('end_date', models.DateField()),
                ('department', apps.fields.ForeignKeyWithOutDBConstraint(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='orgs.orgdepartment')),
            ],
            options={
                'db_table': 'position',
            },
        ),
        migrations.CreateModel(
            name='OrgUnit',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('creator_id', models.CharField(max_length=100, verbose_name='创建人')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('modifier_id', models.CharField(max_length=100, verbose_name='修改人')),
                ('is_del', models.BooleanField(default=False, verbose_name='是否删除')),
                ('delete_time', models.DateTimeField(null=True, verbose_name='删除时间')),
                ('deleter_id', models.CharField(max_length=100, verbose_name='删除人')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('id', apps.fields.LowerCaseShortUUIDField(blank=True, editable=False, max_length=22, primary_key=True, serialize=False)),
                ('begin_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_root', models.BooleanField(default=False)),
                ('parent', apps.fields.ForeignKeyWithOutDBConstraint(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='orgs.orgunit')),
            ],
            options={
                'db_table': 'org_unit',
            },
        ),
        migrations.AddField(
            model_name='orgdepartment',
            name='unit',
            field=apps.fields.ForeignKeyWithOutDBConstraint(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='orgs.orgunit'),
        ),
    ]
